spring:
  application:
    name: maze-be

info:
  app:
    name: maze-be
    description: This application provides a web service that calculates the shortest path within a maze.
    version: 1.0.0

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true
    
logging.level.org.bwgz: DEBUG

---
spring:
    profiles: production

server:
  port: 8443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: mypassword
    keyStoreType: PKCS12
    keyAlias: tomcat

